# Generated by Django 5.2.8 on 2025-11-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='centro_pevi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.centropevi'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante / Ingeniero Junior'), ('PROFESOR', 'Profesor Líder de Proyecto'), ('DIRECTOR_CENTRO', 'Director de Centro PEVI'), ('DIRECTOR_NACIONAL', 'Director Nacional (Líder PEVI)')], default='ESTUDIANTE', max_length=30),
        ),
    ]
