# Generated by Django 5.2.8 on 2026-02-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_usuario_cargo_alter_usuario_centro_pevi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centropevi',
            options={'ordering': ['nombre'], 'verbose_name': 'Centro PEVI', 'verbose_name_plural': 'Centros PEVI'},
        ),
        migrations.AddField(
            model_name='centropevi',
            name='año_vinculacion',
            field=models.PositiveIntegerField(blank=True, help_text='Año en que se unió al programa PEVI', null=True, verbose_name='Año de Vinculación'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='color_primario',
            field=models.CharField(blank=True, default='#1E40AF', help_text='Código hex, ej: #1E40AF', max_length=7, verbose_name='Color Institucional'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del centro y sus capacidades', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='director_cargo',
            field=models.CharField(blank=True, help_text='Ej: PhD. Ingeniería Mecánica', max_length=100, verbose_name='Cargo Académico'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Director'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='director_foto',
            field=models.ImageField(blank=True, null=True, upload_to='centros/directores/', verbose_name='Foto del Director'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='director_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Director'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Ej: Térmica, Eléctrica, Renovables', max_length=255, verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='estudiantes_formados',
            field=models.PositiveIntegerField(default=0, verbose_name='Estudiantes Formados'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='centros/portadas/', verbose_name='Imagen del Campus'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Para mapa interactivo', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='centros/logos/', verbose_name='Logo Institucional'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Para mapa interactivo', null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text='Ej: UNAL, UIS, UNINORTE', max_length=20, verbose_name='Siglas'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='centropevi',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
        migrations.AlterField(
            model_name='centropevi',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre Completo'),
        ),
    ]
