# Generated by Django 5.2.8 on 2026-02-08 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_centropevi_options_centropevi_año_vinculacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESO', 'Acceso'), ('ACTIVIDAD', 'Actividad'), ('SEGURIDAD', 'Seguridad'), ('ERROR', 'Error')], db_index=True, max_length=20)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('VER', 'Ver'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('ESCALADA_BLOQUEADA', 'Escalada de privilegios bloqueada')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username_intento', models.CharField(blank=True, help_text='Username usado en intentos fallidos de login', max_length=150)),
                ('modelo_afectado', models.CharField(blank=True, help_text='Ej: Proyecto, Empresa, Usuario', max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación del objeto', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='gestion.centropevi')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo', 'timestamp'], name='gestion_reg_tipo_ea02f3_idx'), models.Index(fields=['usuario', 'timestamp'], name='gestion_reg_usuario_15eb3b_idx'), models.Index(fields=['accion', 'modelo_afectado'], name='gestion_reg_accion_c5a864_idx')],
            },
        ),
    ]
