# Generated by Django 5.2.8 on 2026-06-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante / Ingeniero Junior'), ('PROFESOR', 'Profesor Líder de Proyecto'), ('DIRECTOR_CENTRO', 'Director de Centro PEVI'), ('DIRECTOR_NACIONAL', 'Director Nacional (Líder PEVI)'), ('COORDINADOR', 'Coordinador General')], default='ESTUDIANTE', max_length=30),
        ),
    ]
