# Generated by Django 5.2.8 on 2026-06-10 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rol_solicitado', models.CharField(choices=[('PROFESOR', 'Profesor Líder de Proyecto'), ('ESTUDIANTE', 'Estudiante / Ingeniero Junior')], default='ESTUDIANTE', max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('justificacion', models.TextField(blank=True, help_text='Motivo o contexto de la solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesada', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.CharField(blank=True, help_text='Nota interna (ej: motivo de rechazo)', max_length=255)),
                ('centro_pevi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='gestion.centropevi')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Usuario',
                'verbose_name_plural': 'Solicitudes de Usuario',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
