# Generated by Django 5.2.8 on 2025-11-19 04:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('sector_productivo', models.CharField(help_text='Ej: Alimentos, Metalmecánica, Textil', max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=150, verbose_name='Nombre Contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email Contacto')),
                ('contacto_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(help_text='Ej: Auditoría Energética Planta 1 - 2025', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'En Formulación'), ('EJECUCION', 'En Ejecución'), ('REVISION', 'En Revisión Interna'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20)),
                ('produccion_total', models.FloatField(default=0, help_text='Producción total en el periodo evaluado')),
                ('unidad_produccion', models.CharField(help_text='Ej: Toneladas, Unidades, m2', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.centropevi', verbose_name='Centro Responsable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='auditorias.empresa')),
                ('equipo', models.ManyToManyField(blank=True, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Ingenieros/Estudiantes Asignados')),
                ('lider_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GasPropano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual_orig', models.FloatField(verbose_name='Consumo Mensual (Ud. Original)')),
                ('consumo_anual_orig', models.FloatField(verbose_name='Consumo Anual (Ud. Original)')),
                ('poder_calorifico', models.FloatField(verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: kJ/m3, MJ/kg', max_length=20, verbose_name='Unidad del PC')),
                ('consumo_mensual_kwh', models.FloatField(verbose_name='Consumo Eq. Mensual (kWh)')),
                ('consumo_anual_kwh', models.FloatField(verbose_name='Consumo Eq. Anual (kWh)')),
                ('costo_kwh_equivalente', models.FloatField(verbose_name='Costo Equivalente ($/kWh)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro GLP',
            },
        ),
        migrations.CreateModel(
            name='GasNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual_orig', models.FloatField(verbose_name='Consumo Mensual (Ud. Original)')),
                ('consumo_anual_orig', models.FloatField(verbose_name='Consumo Anual (Ud. Original)')),
                ('poder_calorifico', models.FloatField(verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: kJ/m3, MJ/kg', max_length=20, verbose_name='Unidad del PC')),
                ('consumo_mensual_kwh', models.FloatField(verbose_name='Consumo Eq. Mensual (kWh)')),
                ('consumo_anual_kwh', models.FloatField(verbose_name='Consumo Eq. Anual (kWh)')),
                ('costo_kwh_equivalente', models.FloatField(verbose_name='Costo Equivalente ($/kWh)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro Gas Natural',
            },
        ),
        migrations.CreateModel(
            name='FuelOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual_orig', models.FloatField(verbose_name='Consumo Mensual (Ud. Original)')),
                ('consumo_anual_orig', models.FloatField(verbose_name='Consumo Anual (Ud. Original)')),
                ('poder_calorifico', models.FloatField(verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: kJ/m3, MJ/kg', max_length=20, verbose_name='Unidad del PC')),
                ('consumo_mensual_kwh', models.FloatField(verbose_name='Consumo Eq. Mensual (kWh)')),
                ('consumo_anual_kwh', models.FloatField(verbose_name='Consumo Eq. Anual (kWh)')),
                ('costo_kwh_equivalente', models.FloatField(verbose_name='Costo Equivalente ($/kWh)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro Fuel Oil',
            },
        ),
        migrations.CreateModel(
            name='Electricidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual', models.FloatField(verbose_name='Consumo Mensual (kWh/mes)')),
                ('consumo_anual', models.FloatField(verbose_name='Consumo Anual (kWh/año)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro Electricidad',
            },
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_proyectos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'jpg', 'png'])])),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nombre del Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='auditorias.proyectoauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual_orig', models.FloatField(verbose_name='Consumo Mensual (Ud. Original)')),
                ('consumo_anual_orig', models.FloatField(verbose_name='Consumo Anual (Ud. Original)')),
                ('poder_calorifico', models.FloatField(verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: kJ/m3, MJ/kg', max_length=20, verbose_name='Unidad del PC')),
                ('consumo_mensual_kwh', models.FloatField(verbose_name='Consumo Eq. Mensual (kWh)')),
                ('consumo_anual_kwh', models.FloatField(verbose_name='Consumo Eq. Anual (kWh)')),
                ('costo_kwh_equivalente', models.FloatField(verbose_name='Costo Equivalente ($/kWh)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro Carbón Mineral',
            },
        ),
        migrations.CreateModel(
            name='Biomasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField(help_text='COP/Unidad', verbose_name='Costo Unitario Promedio')),
                ('costo_mensual_promedio', models.FloatField(verbose_name='Costo Mensual Promedio (COP)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual (COP)')),
                ('factor_emision', models.FloatField(help_text='kgCO2/Unidad', verbose_name='Factor de Emisión (FE)')),
                ('emisiones_totales', models.FloatField(verbose_name='Emisiones Totales (TonCO2/año)')),
                ('consumo_mensual_orig', models.FloatField(verbose_name='Consumo Mensual (Ud. Original)')),
                ('consumo_anual_orig', models.FloatField(verbose_name='Consumo Anual (Ud. Original)')),
                ('poder_calorifico', models.FloatField(verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: kJ/m3, MJ/kg', max_length=20, verbose_name='Unidad del PC')),
                ('consumo_mensual_kwh', models.FloatField(verbose_name='Consumo Eq. Mensual (kWh)')),
                ('consumo_anual_kwh', models.FloatField(verbose_name='Consumo Eq. Anual (kWh)')),
                ('costo_kwh_equivalente', models.FloatField(verbose_name='Costo Equivalente ($/kWh)')),
                ('tipo', models.CharField(default='Genérica', max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Registro Biomasa',
            },
        ),
    ]
