# Generated by Django 5.2.8 on 2025-11-19 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('sector_productivo', models.CharField(help_text='Ej: Alimentos, Metalmecánica, Textil', max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=150, verbose_name='Nombre Contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email Contacto')),
                ('contacto_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(help_text='Ej: Auditoría Energética Planta 1 - 2025', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'En Formulación'), ('EJECUCION', 'En Ejecución'), ('REVISION', 'En Revisión Interna'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20)),
                ('produccion_total', models.FloatField(default=0, help_text='Producción total en el periodo evaluado')),
                ('unidad_produccion', models.CharField(help_text='Ej: Toneladas, Unidades, m2', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.centropevi', verbose_name='Centro Responsable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='auditorias.empresa')),
                ('equipo', models.ManyToManyField(blank=True, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Ingenieros/Estudiantes Asignados')),
                ('lider_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_proyectos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'jpg', 'png'])])),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nombre del Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='auditorias.proyectoauditoria')),
            ],
        ),
    ]
