# Generated by Django 5.2.8 on 2025-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoauditoria',
            name='produccion_total',
            field=models.FloatField(blank=True, default=0, help_text='Producción total en el periodo evaluado', null=True),
        ),
        migrations.AlterField(
            model_name='proyectoauditoria',
            name='unidad_produccion',
            field=models.CharField(blank=True, help_text='Ej: Toneladas, Unidades, m2', max_length=50, null=True),
        ),
    ]
