# Generated by Django 5.2.8 on 2025-11-19 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('poder_calorifico', models.FloatField(help_text='Energía por unidad de masa/volumen', verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: MJ/kg, kJ/m3, kWh/gal', max_length=20)),
                ('tipo_biomasa', models.CharField(default='Genérica', help_text='Ej: Bagazo, Cisco, Leña', max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Biomasa / Bagazo',
                'verbose_name_plural': 'Biomasa',
            },
        ),
        migrations.CreateModel(
            name='CarbonMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('poder_calorifico', models.FloatField(help_text='Energía por unidad de masa/volumen', verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: MJ/kg, kJ/m3, kWh/gal', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Carbón Mineral',
                'verbose_name_plural': 'Carbón Mineral',
            },
        ),
        migrations.CreateModel(
            name='Electricidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Electricidad',
                'verbose_name_plural': 'Electricidad',
            },
        ),
        migrations.CreateModel(
            name='FuelOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('poder_calorifico', models.FloatField(help_text='Energía por unidad de masa/volumen', verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: MJ/kg, kJ/m3, kWh/gal', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Fuel Oil / Diesel',
                'verbose_name_plural': 'Fuel Oil / Diesel',
            },
        ),
        migrations.CreateModel(
            name='GasNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('poder_calorifico', models.FloatField(help_text='Energía por unidad de masa/volumen', verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: MJ/kg, kJ/m3, kWh/gal', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Gas Natural',
                'verbose_name_plural': 'Gas Natural',
            },
        ),
        migrations.CreateModel(
            name='GasPropano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_promedio_mensual', models.FloatField(verbose_name='Consumo Mensual Promedio')),
                ('consumo_total_anual', models.FloatField(verbose_name='Consumo Total Anual')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario Promedio ($/Unidad)')),
                ('costo_total_anual', models.FloatField(verbose_name='Costo Total Anual ($)')),
                ('factor_emision', models.FloatField(help_text='Factor de Emisión (kgCO2/Unidad)', verbose_name='FE')),
                ('poder_calorifico', models.FloatField(help_text='Energía por unidad de masa/volumen', verbose_name='Poder Calorífico (PC)')),
                ('unidad_pc', models.CharField(help_text='Ej: MJ/kg, kJ/m3, kWh/gal', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Gas Propano (GLP)',
                'verbose_name_plural': 'Gas Propano (GLP)',
            },
        ),
    ]
