# Generated by Django 5.2.8 on 2025-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_alter_proyectoauditoria_produccion_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomasa',
            name='poder_calorifico',
            field=models.FloatField(help_text='Unidad Estandarizada: kJ/m³ (Gases/Líq) o kJ/kg (Sólidos)', verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='biomasa',
            name='unidad_pc',
            field=models.CharField(default='Estándar', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='carbonmineral',
            name='poder_calorifico',
            field=models.FloatField(help_text='Unidad Estandarizada: kJ/m³ (Gases/Líq) o kJ/kg (Sólidos)', verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='carbonmineral',
            name='unidad_pc',
            field=models.CharField(default='Estándar', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='fueloil',
            name='poder_calorifico',
            field=models.FloatField(help_text='Unidad Estandarizada: kJ/m³ (Gases/Líq) o kJ/kg (Sólidos)', verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='fueloil',
            name='unidad_pc',
            field=models.CharField(default='Estándar', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='gasnatural',
            name='poder_calorifico',
            field=models.FloatField(help_text='Unidad Estandarizada: kJ/m³ (Gases/Líq) o kJ/kg (Sólidos)', verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='gasnatural',
            name='unidad_pc',
            field=models.CharField(default='Estándar', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='gaspropano',
            name='poder_calorifico',
            field=models.FloatField(help_text='Unidad Estandarizada: kJ/m³ (Gases/Líq) o kJ/kg (Sólidos)', verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='gaspropano',
            name='unidad_pc',
            field=models.CharField(default='Estándar', editable=False, max_length=20),
        ),
    ]
