# Generated by Django 5.2.8 on 2026-02-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_alter_biomasa_poder_calorifico_and_more'),
        ('gestion', '0002_alter_usuario_cargo_alter_usuario_centro_pevi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='gestion.centropevi', verbose_name='Centro PEVI'),
        ),
    ]
