# Generated by Django 5.2.8 on 2026-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0004_add_centro_to_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoauditoria',
            name='fase',
            field=models.CharField(blank=True, choices=[('FASE_1', 'Fase 1'), ('FASE_2', 'Fase 2'), ('FASE_3', 'Fase 3'), ('FASE_4', 'Fase 4')], max_length=10, null=True, verbose_name='Fase del Programa'),
        ),
        migrations.AlterField(
            model_name='biomasa',
            name='poder_calorifico',
            field=models.FloatField(verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='carbonmineral',
            name='poder_calorifico',
            field=models.FloatField(verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='fueloil',
            name='poder_calorifico',
            field=models.FloatField(verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='gasnatural',
            name='poder_calorifico',
            field=models.FloatField(verbose_name='Poder Calorífico (PC)'),
        ),
        migrations.AlterField(
            model_name='gaspropano',
            name='poder_calorifico',
            field=models.FloatField(verbose_name='Poder Calorífico (PC)'),
        ),
    ]
