# Generated by Django 5.2.8 on 2026-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0005_proyectoauditoria_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomasa',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
        migrations.AddField(
            model_name='carbonmineral',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
        migrations.AddField(
            model_name='electricidad',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
        migrations.AddField(
            model_name='fueloil',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
        migrations.AddField(
            model_name='gasnatural',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
        migrations.AddField(
            model_name='gaspropano',
            name='porcentaje_reduccion',
            field=models.FloatField(default=0, help_text='Porcentaje de reducción objetivo para este energético', verbose_name='Meta de Reducción (%)'),
        ),
    ]
