# Generated by Django 5.2.8 on 2026-02-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0006_biomasa_porcentaje_reduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='OPM')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('energetico', models.CharField(choices=[('ELECTRICIDAD', 'Electricidad'), ('GAS_NATURAL', 'Gas Natural'), ('CARBON', 'Carbón Mineral'), ('FUEL_OIL', 'Fuel Oil'), ('BIOMASA', 'Biomasa'), ('GLP', 'Gas Propano (GLP)'), ('OTRO', 'Otro')], max_length=20)),
                ('ahorro_energia', models.FloatField(default=0, verbose_name='Ahorro Energía (kWh/año)')),
                ('costos_evitados', models.FloatField(default=0, verbose_name='Costos Evitados (MCOP/año)')),
                ('emisiones_evitadas', models.FloatField(default=0, verbose_name='Emisiones Evitadas (TonCO2/año)')),
                ('inversion', models.FloatField(default=0, verbose_name='Inversión (COP)')),
                ('vpn', models.FloatField(default=0, verbose_name='VPN (COP)')),
                ('tir', models.FloatField(default=0, verbose_name='TIR (%)')),
                ('payback', models.FloatField(default=0, verbose_name='Payback (meses)')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_mejora', to='auditorias.proyectoauditoria')),
            ],
            options={
                'verbose_name': 'Oportunidad de Mejora',
                'verbose_name_plural': 'Oportunidades de Mejora',
                'ordering': ['codigo'],
            },
        ),
    ]
