"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# cast=Csv() permite leer la lista separada por comas del .env
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'gestion',
    'auditorias',
    'metricas',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.ContentSecurityPolicyMiddleware',  # CSP Headers
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de Usuario Personalizado
AUTH_USER_MODEL = 'gestion.Usuario'


# Redirección tras login/logout
LOGIN_REDIRECT_URL = 'dashboard'      # Redirige a /app/ después de login
LOGOUT_REDIRECT_URL = 'login'   # Redirige al login después de logout

# Mapeo de tags de mensajes para Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

AUTHENTICATION_BACKENDS = [
    'gestion.backends.EmailOrUsernameModelBackend',  # Nuestro backend personalizado
    'django.contrib.auth.backends.ModelBackend',     # El default (por seguridad/fallback)
]


# CSRF Trusted Origins (requerido para Django 4.0+ con HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://pevicolombia.com',
    'https://www.pevicolombia.com',
]


# ==============================================================================
# STATIC & MEDIA FILES - Configuración Híbrida (Local vs S3)
# ==============================================================================

STATICFILES_DIRS = [BASE_DIR / 'static']

if DEBUG:
    # -------------------------------------------------------------------------
    # MODO DESARROLLO (LOCAL)
    # -------------------------------------------------------------------------
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

else:
    # -------------------------------------------------------------------------
    # MODO PRODUCCIÓN (AWS S3)
    # -------------------------------------------------------------------------
    from storages.backends.s3boto3 import S3Boto3Storage

    # Configuración AWS (credenciales via IAM Role del EC2)
    AWS_STORAGE_BUCKET_NAME = 'vadomdata'
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False  # URLs públicas sin firma

    # Prefijo del cliente (carpeta en S3)
    S3_PREFIX = config('S3_CLIENT_PREFIX', default='pevi')

    # Storage personalizado para estáticos
    class StaticStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/static'
        default_acl = None

    # Storage personalizado para media (archivos subidos)
    class MediaStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/media'
        default_acl = None

    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_PREFIX}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_PREFIX}/media/'

    STORAGES = {
        "default": {"BACKEND": "config.settings.MediaStorage"},
        "staticfiles": {"BACKEND": "config.settings.StaticStorage"},
    }


# ==============================================================================
# SISTEMA DE LOGS
# ==============================================================================

# Crear carpeta de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
try:
    LOGS_DIR.mkdir(exist_ok=True)
except PermissionError:
    pass  # En producción, la carpeta ya debe existir con permisos correctos

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Formateadores: cómo se ve cada línea del log
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} | {message}',
            'style': '{',
        },
        'security': {
            'format': '[{asctime}] SEGURIDAD | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # Handlers: a dónde van los logs
    'handlers': {
        # Consola (desarrollo)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },

        # Archivo de accesos (login, logout)
        'acceso_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'acceso.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Archivo de actividad (CRUD)
        'actividad_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'actividad.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Archivo de errores
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errores.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },

        # Archivo de seguridad
        'seguridad_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'seguridad.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 10,
            'formatter': 'security',
            'encoding': 'utf-8',
        },
    },

    # Loggers: categorías de logs
    'loggers': {
        # Log de accesos
        'pevi.acceso': {
            'handlers': ['acceso_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },

        # Log de actividad
        'pevi.actividad': {
            'handlers': ['actividad_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },

        # Log de errores
        'pevi.errores': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },

        # Log de seguridad
        'pevi.seguridad': {
            'handlers': ['seguridad_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Errores de Django
        'django': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },

        # Requests de Django (opcional, muy verbose)
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}